### ISSUE TITLE
Required handle "editor" is missing, while cache is enabled

### ISSUE THREAD

**Issue by kubaceg** [Jarlssen/Jarlssen_ChooserWidget#4] opened 2014-08-27 09:33 UTC
Hello, I have error

`Required handle "editor" is missing. You have to add the handle in the layout in favor to have working chooser.` on `admin/tiles/new` while i have active cache in Magento.... When I flush whole cache it works only for 1st time. Anybody knows the solution?

**Comment by yireo** [comment] 2015-05-04 09:41
I can confirm that the issue of the "editor" handle missing with cache enabled, still exists. The specific cache-tag is the "Layout" cache. When this cache is enabled, all "update" calls are actually removed from the list of handles, and only the real handles (so the root-handles, just under the "layout" XML-element) are left.

I've tried to find another way to solve this, but found none. When the XML-layout is cached, there is simply no reference at all to something called "editor", because it is all compiled-in and merged with the final XML-layout.

Because the check for an "editor" handle is something that concerns developers instead of end-users, I would suggest to simply remove the entire check (so the entire _checkRequiredHandle method). When adding your (great!) module to custom code, you will need to read the docs anyway to make it work - and the docs already state that the "update" handle is needed to make it work. Having a real-time check seems less needed.

**Comment by ceckoslab** [comment] 2015-05-14 14:27
@kubaceg and @yireo ,

Thanks for the push!

Issue is resolved!

**Closed by ceckoslab** 2015-05-14 14:27 UTC
